import { Product } from "./Mockdata";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    type: "vape",
    name: "XROS 3 Mini",
    brand: "Vaporesso",
    price: 1200,
    img: "/Pod.jpg",
    description: "Вейп система,с отличными качествами и приемуществами",
    batteryCapacity: 1000,
    maxPower: 16,
    color: "Space Grey",
    InStock : true,
  },
  {
    id: "2",
    type: "liquid",
    name: "Husky Salt",
    brand: "Voodoo Lab",
    price: 450,
    img: "/Jija.png",
    description: "Жижа на основе арбуза,с приятными холодком",
    volume: 30,
    nicotine: 20,
    flavor: ["Ice", "WaterMelon"],
    InStock : false,
  },
  {
      id: "3",
    type: "consumables",
    name: "Automizer",
    brand: "Aspire",
    description  : 'испаритель для качественного погружения в мир вкусовых качеств',
    price: 400,
    img: "/Automizer.jpg",
    InStock : true,
  },
   {
    id: "4",
    type: "vape",
    name: "XROS 3 Mini",
    brand: "Vaporesso",
    price: 1200,
    img: "/Pod.jpg",
    description: "Vape",
    batteryCapacity: 1000,
    maxPower: 16,
    color: "Space Grey",
    InStock : true,
  }, {
    id: "5",
    type: "vape",
    name: "XROS 3 Mini",
    brand: "Vaporesso",
    price: 1200,
    img: "/Pod.jpg",
    description: "Vape",
    batteryCapacity: 1000,
    maxPower: 16,
    color: "Space Grey",
    InStock : true,
  },
   {
    id: "6",
    type: "vape",
    name: "XROS 3 Mini",
    brand: "Vaporesso",
    price: 1200,
    img: "/Pod.jpg",
    description: "Vape",
    batteryCapacity: 1000,
    maxPower: 16,
    color: "Space Grey",
    InStock : true,
  },
   {
    id: "7",
    type: "vape",
    name: "XROS 3 Mini",
    brand: "Vaporesso",
    price: 1200,
    img: "/Pod.jpg",
    description: "Vape",
    batteryCapacity: 1000,
    maxPower: 16,
    color: "Space Grey",
    InStock : true,
  },
];