import { Product } from "./Mockdata";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    type: "vape",
    name: "XROS 3 Mini",
    brand: "Vaporesso",
    price: 1200,
    img: "/Pod.jpg",
    description: "Компактная POD-система с регулировкой затяжки",
    batteryCapacity: 1000,
    maxPower: 16,
    color: "Space Grey",
    InStock: true,
    CoilResistence: 0.4,
    TankCapacity: 4,
    LikeCount: 47,
  },
  {
    id: "2",
    type: "liquid",
    name: "Husky Salt Arctic",
    brand: "Voodoo Lab",
    price: 450,
    img: "/Jija.png",
    description: "Освежающая жижа на основе арбуза с ментолом",
    volume: 30,
    nicotine: 20,
    flavor: ["Ice", "WaterMelon"],
    InStock: false,
    Icelevel: 75,
    LikeCount: 0,
  },
  {
    id: "3",
    type: "consumables",
    name: "NexM Mesh Coil 0.4Ω",
    brand: "Aspire",
    description: "Сменный испаритель с сетчатой намоткой для AVP Pro",
    price: 400,
    img: "/Automizer.jpg",
    InStock: true,
    LikeCount: 0,
  },
  {
    id: "4",
    type: "vape",
    name: "Drag S Pro",
    brand: "Voopoo",
    price: 1850,
    img: "/Pod.jpg",
    description: "Мощный боксмод с регулируемой мощностью до 80W",
    batteryCapacity: 3000,
    maxPower: 80,
    color: "Carbon Fiber",
    InStock: true,
    CoilResistence: 0.3,
    TankCapacity: 5.5,
    LikeCount: 72,
  },
  {
    id: "5",
    type: "vape",
    name: "RPM 4",
    brand: "Smok",
    price: 1450,
    img: "/Pod.jpg",
    description: "POD-мод с двумя типами испарителей в комплекте",
    batteryCapacity: 1650,
    maxPower: 60,
    color: "Silver",
    InStock: true,
    CoilResistence: 0.25,
    TankCapacity: 4.5,
    LikeCount: 0,
  },
  {
    id: "6",
    type: "vape",
    name: "Gen Nano",
    brand: "Vaporesso",
    price: 1100,
    img: "/Pod.jpg",
    description: "Компактный боксмод с быстрой зарядкой 2A",
    batteryCapacity: 2000,
    maxPower: 40,
    color: "Matte Blue",
    InStock: true,
    CoilResistence: 0.5,
    TankCapacity: 3.5,
    LikeCount: 0,
  },
  {
    id: "7",
    type: "vape",
    name: "Obelisk 60",
    brand: "GeekVape",
    price: 1600,
    img: "/Pod.jpg",
    description: "POD-система с защитой IP68 и ударопрочным корпусом",
    batteryCapacity: 2200,
    maxPower: 60,
    color: "Red",
    InStock: true,
    CoilResistence: 0.4,
    TankCapacity: 4,
    LikeCount: 58,
  },
  {
    id: "8",
    type: "vape",
    name: "Thallo S",
    brand: "Smoant",
    price: 1350,
    img: "/Pod.jpg",
    description: "Элегантный POD с сенсорным дисплеем",
    batteryCapacity: 2500,
    maxPower: 80,
    color: "Rainbow",
    InStock: true,
    CoilResistence: 0.35,
    TankCapacity: 5,
    LikeCount: 0,
  },
  {
    id: "9",
    type: "vape",
    name: "Doric 20",
    brand: "Voopoo",
    price: 850,
    img: "/Pod.jpg",
    description: "Минималистичный POD с магнитным картриджем",
    batteryCapacity: 1500,
    maxPower: 18,
    color: "Black",
    InStock: true,
    CoilResistence: 0.7,
    TankCapacity: 2,
    LikeCount: 0,
  },
  {
    id: "10",
    type: "vape",
    name: "Flask Mini",
    brand: "HellVape",
    price: 990,
    img: "/Pod.jpg",
    description: "Уникальный дизайн в форме фляги с верхним обдувом",
    batteryCapacity: 1400,
    maxPower: 50,
    color: "Bronze",
    InStock: true,
    CoilResistence: 0.5,
    TankCapacity: 3.5,
    LikeCount: 23,
  },
  {
    id: "11",
    type: "vape",
    name: "Luxe X Pro",
    brand: "Vaporesso",
    price: 1700,
    img: "/Pod.jpg",
    description: "Премиум POD с RGB подсветкой и регулировкой потока воздуха",
    batteryCapacity: 1800,
    maxPower: 40,
    color: "Purple Haze",
    InStock: false,
    CoilResistence: 0.6,
    TankCapacity: 5,
    LikeCount: 89,
  },
  {
    id: "12",
    type: "liquid",
    name: "Tropic Thunder",
    brand: "MNGO",
    price: 520,
    img: "/Jija.png",
    description: "Экзотический микс манго и маракуйи",
    volume: 50,
    nicotine: 12,
    flavor: ["Mango", "Passion Fruit"],
    InStock: true,
    Icelevel: 25,
    LikeCount: 0,
  },
  {
    id: "13",
    type: "liquid",
    name: "Berry Bomb Ice",
    brand: "Bad Drip",
    price: 650,
    img: "/Jija.png",
    description: "Лесные ягоды с ледяным финалом",
    volume: 30,
    nicotine: 18,
    flavor: ["Blueberry", "Raspberry", "Blackberry"],
    InStock: true,
    Icelevel: 100,
    LikeCount: 65,
  },
  {
    id: "14",
    type: "liquid",
    name: "Virginia Tobacco",
    brand: "Dinner Lady",
    price: 580,
    img: "/Jija.png",
    description: "Классический табак с карамельной подсласткой",
    volume: 50,
    nicotine: 6,
    flavor: ["Tobacco", "Caramel"],
    InStock: true,
    Icelevel: 0,
    LikeCount: 0,
  },
  {
    id: "15",
    type: "liquid",
    name: "Coconut Wave",
    brand: "Pachamama",
    price: 490,
    img: "/Jija.png",
    description: "Тропический кокосовый микс с персиком",
    volume: 100,
    nicotine: 3,
    flavor: ["Coconut", "Peach", "Melon"],
    InStock: true,
    Icelevel: 50,
    LikeCount: 0,
  },
  {
    id: "16",
    type: "liquid",
    name: "Lemon Pie",
    brand: "Sweet Tooth",
    price: 430,
    img: "/Jija.png",
    description: "Домашний лимонный пирог с меренгой",
    volume: 30,
    nicotine: 20,
    flavor: ["Lemon", "Cream", "Biscuit"],
    InStock: true,
    Icelevel: 0,
    LikeCount: 0,
  },
  {
    id: "17",
    type: "liquid",
    name: "Grape Drank",
    brand: "Pinup Vapez",
    price: 510,
    img: "/Jija.png",
    description: "Виноградный лимонад со льдом",
    volume: 50,
    nicotine: 10,
    flavor: ["Grape", "Lemonade", "Ice"],
    InStock: true,
    Icelevel: 75,
    LikeCount: 34,
  },
  {
    id: "18",
    type: "liquid",
    name: "Strawberry Cheesecake",
    brand: "Milkman",
    price: 620,
    img: "/Jija.png",
    description: "Клубника в сливочном чизкейке",
    volume: 100,
    nicotine: 6,
    flavor: ["Strawberry", "Cheesecake", "Cream"],
    InStock: true,
    Icelevel: 0,
    LikeCount: 0,
  },
  {
    id: "19",
    type: "liquid",
    name: "Banana Milk",
    brand: "Cuttwood",
    price: 550,
    img: "/Jija.png",
    description: "Сливочный банан как в детстве",
    volume: 50,
    nicotine: 12,
    flavor: ["Banana", "Milk", "Vanilla"],
    InStock: true,
    Icelevel: 0,
    LikeCount: 0,
  },
  {
    id: "20",
    type: "liquid",
    name: "Frosty Cola",
    brand: "Atomic",
    price: 380,
    img: "/Jija.png",
    description: "Классическая кола со льдом",
    volume: 30,
    nicotine: 20,
    flavor: ["Cola", "Ice"],
    InStock: true,
    Icelevel: 100,
    LikeCount: 0,
  },
  {
    id: "21",
    type: "liquid",
    name: "Watermelon Lime",
    brand: "Naked",
    price: 480,
    img: "/Jija.png",
    description: "Освежающий арбуз с лаймом",
    volume: 50,
    nicotine: 10,
    flavor: ["Watermelon", "Lime"],
    InStock: true,
    Icelevel: 50,
    LikeCount: 0,
  },
  {
    id: "22",
    type: "consumables",
    name: "GT Meshed Coil 0.6Ω",
    brand: "GeekVape",
    description: "Испаритель для Aegis Boost и Hero Mini",
    price: 350,
    img: "/Automizer.jpg",
    InStock: true,
    LikeCount: 0,
  },
  {
    id: "23",
    type: "consumables",
    name: "RPM2 Coil 0.8Ω",
    brand: "Smok",
    description: "MTL испаритель для RPM 2 и RPM 60",
    price: 280,
    img: "/Automizer.jpg",
    InStock: true,
    LikeCount: 0,
  },
  {
    id: "24",
    type: "consumables",
    name: "GT4 Meshed Coil 0.15Ω",
    brand: "GeekVape",
    description: "DL испаритель для SKY SOLO",
    price: 380,
    img: "/Automizer.jpg",
    InStock: true,
    LikeCount: 0,
  },
  {
    id: "25",
    type: "consumables",
    name: "V9 Mesh Coil 0.4Ω",
    brand: "Voopoo",
    description: "Испаритель для Drag S/X серии",
    price: 320,
    img: "/Automizer.jpg",
    InStock: true,
    LikeCount: 0,
  },
  {
    id: "26",
    type: "consumables",
    name: "NexM Pro Coil 0.8Ω",
    brand: "Aspire",
    description: "MTL испаритель для Odysseus и K2 Max",
    price: 290,
    img: "/Automizer.jpg",
    InStock: true,
    LikeCount: 42,
  },
  {
    id: "27",
    type: "consumables",
    name: "QF Meshed Coil 0.4Ω",
    brand: "Vaporesso",
    description: "Испаритель дляARGET и iTank серии",
    price: 340,
    img: "/Automizer.jpg",
    InStock: false,
    LikeCount: 0,
  },
  {
    id: "28",
    type: "consumables",
    name: "P-Series Coil 0.3Ω",
    brand: "Smoant",
    description: "DL испаритель для Battlestar и Charon",
    price: 310,
    img: "/Automizer.jpg",
    InStock: true,
    LikeCount: 0,
  },
  {
    id: "29",
    type: "consumables",
    name: "HP Coil 1.2Ω",
    brand: "Innokin",
    description: "MTL испаритель для Zenith и Zlide",
    price: 250,
    img: "/Automizer.jpg",
    InStock: true,
    LikeCount: 0,
  },
  {
    id: "30",
    type: "consumables",
    name: "NS Coil 1.5Ω",
    brand: "Freemax",
    description: "MTL испаритель для Onixx и Onixx GZ",
    price: 270,
    img: "/Automizer.jpg",
    InStock: true,
    LikeCount: 0,
  },
  {
    id: "31",
    type: "consumables",
    name: "DTL Coil 0.15Ω",
    brand: "LostVape",
    description: "DL испаритель для Orion Plus и Ursa",
    price: 360,
    img: "/Automizer.jpg",
    InStock: true,
    LikeCount: 0,
  },
];
