export const PAGES = {
    HOME: "/",
    CATALOG: "/catalog",
    BRANDS: "/brands",
    CART: "/cart",
    MATCHER: "/matcher",
    ABOUT: "/about",
    AUTH:"/auth",
    FAVORITES: "/favorites",
    LIKES : "/likes",
    USERPROFILE: "/userprofile",
    CHECKOUT: "/checkout",

    ADMIN: "/admin",
    ADMIN_PRODUCTS: "/admin/products",
    ADMIN_PRODUCTS_CREATE: "/admin/products/create",
    ADMIN_ORDERS: "/admin/orders",
    ADMIN_USERS: "/admin/users",
    ADMIN_ANALYTICS: "/admin/analytics",
    ADMIN_BRANDS: "/admin/brands",
    ADMIN_CATEGORIES: "/admin/categories",
    ADMIN_FLAVORS: "/admin/flavors",
    ADMIN_TAGS: "/admin/tags",
    ADMIN_COUNTRIES: "/admin/countries",
    ADMIN_IMAGES: "/admin/images",

    getProduct: (id: string) => `/catalog/${id}`,
    getCatalog: (sort?: string) => sort ? `/catalog?sort=${sort}` : "/catalog",
    getBrand: (id: number) => `/brands/${id}`,
    getAdminOrder: (id: number) => `/admin/orders/${id}`,
    getAdminUser: (id: number) => `/admin/users/${id}`,
    getAdminEditProduct: (id: number) => `/admin/products/${id}/edit`,
    getAdminBrand: (id: number) => `/admin/brands/${id}`,
    getAdminCategory: (id: number) => `/admin/categories/${id}`,
};